#!/usr/bin/env bash
# doing some very beneficial redirection on nginx web server

apt-get update
apt-get install -y nginx
echo "some text?" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.instagram.com/rahofahazem/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
