#!/usr/bin/env bash
# Double the number of webservers

apt-get update
apt-get install -y nginx
service nginx start
mkdir /etc/nginx/html
echo "some text?" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.instagram.com/rahofahazem/;
    }
    error_page 404 /404.html;
    location = /404.html{
	    root /etc/nginx/html;
	    internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
