#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install -y haproxy
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 408045-web-01 54.164.162.231:80 check
    server 408045-web-02 54.87.210.192:80 check
EOL
sudo service haproxy restart
