#!/usr/bin/env bash
#print Best School 10 times & for the 9th iteration print & then Hi on a new line.

i=0
while ((i < 10))
do
  if ((i == 8))
  then
       echo "Hi"
  else
       echo "Best School"
  fi
  ((i+=1))
done
